# Generated by Django 4.1.6 on 2023-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data atualização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='entry_date',
            field=models.DateTimeField(auto_created=True, default=None, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data atualização'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='entry_date',
            field=models.DateTimeField(auto_created=True, default=None, verbose_name='Data entrada'),
        ),
    ]
