# Generated by Django 4.1.6 on 2023-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='is_entry',
            field=models.BooleanField(default=True),
        ),
    ]
